### ISSUE TITLE
Viper4android Fx for S21 U

### ISSUE THREAD

**Issue by SaFTaZeeN** [LeeXDA21/BeyondROM_Hub#12]
**Describe the feature**
Adding Viper4android (old & new app) sound Mod  for S21 U

 - Device: [e.g. Galaxy S21 Ultra 5G]
 - Model: [e.g. G998B]

**Comment by LeeXDA21** [comment]
@SaFTaZeeN Not enough info, V4A is in modpack

**Comment by SaFTaZeeN** [comment]
I know but it's for older version of Beyond Rom

**Comment by LeeXDA21** [comment]
@SaFTaZeeN Modpack can be used to install V4A, V4A will not be added to the main rom installation.
