### ISSUE TITLE
[BUG] System apps crash & screenshot loop after dirty flash

### ISSUE THREAD

**Issue by ThisIsRex** [LeeXDA21/BeyondROM_Hub#14]
**Describe the bug**
Occured while upgrading from BeyondROM 2.4 to 2.5

**To Reproduce**
1. Download stock rom
2. Flash it and twrp via odin
3. Install using dirty flash, tick all apps except Samsung dex
4. Reboot sytem

**Expected behavior**
Successful update

**Actual behavior**
After boot the following apps crashing:
1. com.samsung.android.smartsuggestions.App
2. android.process.media
3. Groups
4. Application information
5. res/mipmap-xxhdpi/ic_launcher.webp
When I try to take a screenshot, a system does it several times and does not save it, Albums doesn't work

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device:  Galaxy S21 Ultra 5G
 - Model: SM-G998B/DS

**Comment by Ushie** [comment]
@ThisIsRex Are you using any magisk modules?

**Comment by ThisIsRex** [comment]
> @ThisIsRex Are you using any magisk modules?

Yes, LSPosed, MagiskHide Props Config, Universal SafetyNet Fix, Lucky Patcher with modded Google Play and LSPosed patches applied

**Comment by LeeXDA21** [comment]
@ThisIsRex Remove them.
