### ISSUE TITLE
[BUG] Random Reboots

### ISSUE THREAD

**Issue by Uniquelegacy** [LeeXDA21/BeyondROM_Hub#9]
**Describe the bug**
My phone is randomly rebooting. I have no idea what is causing the issue. I am running the latest beyond rom with stock kernel. The apps I have on my phone are few. But even on fresh install with no apps, it still reboots. I'm willing to send as much information to have the issue looked at, because I'm unsure where the issue lies. I have done a complete clean install of the latest beyond rom. 

**To Reproduce**
To reproduce the error, its so random, sometimes it goes 8 hours without any reboots, but just like that it will reboot 5 times in an hour. 
l just sit on the table and reboot on its own. 
**Expected behavior**

**Screenshots**
Add screenshots to help explain your problem.

**Smartphone (please complete the following information):**
 - Device: Galaxy  S20 + 5G
 - Model: SM-G986B

**Additional context**
- Gather logs by using [LoggingKit](https://github.com/Lethany/BeyondROM_Hub/releases) when applicable
[All logs.zip](https://github.com/LeeXDA21/BeyondROM_Hub/files/7927345/All.logs.zip)

**Comment by LeeXDA21** [comment]
@Uniquelegacy Hi, thanks for the report, I will take a look at your logs and see if I can debug the issue and get back to you.

**Comment by Uniquelegacy** [comment]
Thank you for your time. I appreciate your kindness.

**Comment by LeeXDA21** [comment]
@Uniquelegacy Please flash this zip in TWRP.
[G98X_RebootFix.zip](https://github.com/LeeXDA21/BeyondROM_Hub/files/7927435/G98X_RebootFix.zip)
)

**Comment by Uniquelegacy** [comment]
It rebooted upon installing, heres a look at the new logs
[new logs.zip](https://github.com/LeeXDA21/BeyondROM_Hub/files/7927560/new.logs.zip)

**Comment by LeeXDA21** [comment]
@Uniquelegacy A public hotfix has been issued and this will now be closed and marked as resolved. Thanks for actually reading and reporting an issue correctly.
